CORE_TOP = $(CORE_GENERATOR)
CORE_SIM_TOP = replay

OBJ_CORE_RTL_V = $(CORE_GENERATOR_ADDON)/src/$(CORE_TOP).v
OBJ_CORE_MACROS = $(CORE_GENERATOR_ADDON)/src/replay.macros.json
OBJ_CORE_SIM_FILES = $(CORE_GENERATOR_ADDON)/src/replay.v
OBJ_CORE_SIM_MACRO_FILES = $(CORE_GENERATOR_ADDON)/src/replay.macros.v
