CORE_TOP = $(CORE_GENERATOR)
CORE_SIM_TOP = replay

OBJ_CORE_RTL_V = $(CORE_GENERATOR_ADDON)/src/$(CORE_TOP).v
OBJ_CORE_MEMORY_CONF = $(CORE_GENERATOR_ADDON)/src/$(CORE_TOP).conf
OBJ_CORE_MACROS = $(OBJ_CORE_DIR)/plsi-generated/$(CORE_TOP).macros.json
OBJ_CORE_SIM_FILES = $(CORE_GENERATOR_ADDON)/src/replay.v
OBJ_CORE_SIM_MACRO_FILES = $(OBJ_CORE_DIR)/plsi-generated/$(CORE_TOP).macros.v
